INSERT INTO app_settings (
  id,
  openai_api_key,
  openai_base_url,
  llm_model,
  llm_api_style,
  embedding_api_key,
  embedding_base_url,
  embedding_model,
  embedding_dimensions,
  smtp_host,
  smtp_port,
  smtp_secure,
  smtp_user,
  smtp_pass,
  email_from,
  email_from_name
) VALUES (
  TRUE,
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15
)
ON CONFLICT (id)
DO UPDATE SET
  openai_api_key = EXCLUDED.openai_api_key,
  openai_base_url = EXCLUDED.openai_base_url,
  llm_model = EXCLUDED.llm_model,
  llm_api_style = EXCLUDED.llm_api_style,
  embedding_api_key = EXCLUDED.embedding_api_key,
  embedding_base_url = EXCLUDED.embedding_base_url,
  embedding_model = EXCLUDED.embedding_model,
  embedding_dimensions = EXCLUDED.embedding_dimensions,
  smtp_host = EXCLUDED.smtp_host,
  smtp_port = EXCLUDED.smtp_port,
  smtp_secure = EXCLUDED.smtp_secure,
  smtp_user = EXCLUDED.smtp_user,
  smtp_pass = EXCLUDED.smtp_pass,
  email_from = EXCLUDED.email_from,
  email_from_name = EXCLUDED.email_from_name,
  updated_at = NOW()
RETURNING
  openai_api_key,
  openai_base_url,
  llm_model,
  llm_api_style,
  embedding_api_key,
  embedding_base_url,
  embedding_model,
  embedding_dimensions,
  smtp_host,
  smtp_port,
  smtp_secure,
  smtp_user,
  smtp_pass,
  email_from,
  email_from_name,
  updated_at;
